apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana 
data:
  grafana.ini: |
    [auth]
    # Configuración de usuario y contraseña de Grafana
    username = admin
    password = Secreto1!
